### ISSUE TITLE
Validated content feedback from @ericzolf

### ISSUE THREAD

**Issue by swapdisk** [redhat-cop/infra.lvm_snapshots#37]
After a quick check:

1. not all points have been ticked, what is exactly the status?
2. I find the idea to name the collection like one of the roles questionable, perhaps a better name is possible, covering all aspects of the collection?
3. the variables haven't been named according to standard, with proper prefix
4. the tasks name are not prefixed with the name of the task file
5. the `lvm_snapshots` role is IMHO too complex and should be split into one role for each action to keep it/them nice and tidy (and avoid too many skipped tasks)

_Originally posted by @ericzolf in https://github.com/ansible/validated-content-discussion/issues/20#issuecomment-1854018555_

**Comment by ygalblum** [comment]
I like the idea of splitting the `lvm_snaphosts` role. Furthermore, I found that it contains the actions `check_for_resize` and `resize` which should be removed. `resize` is not even implemented in this role and they are both actually implemented in the `shrink_lv` role.

Item 3 seems required (though not sure why the `ansible-lint` did not err on it). Not sure is item 4 is part of the standard and to me looks redundant, but I don't mind complying.

We need to discuss if the collections' name is still correct, though I understand your concern about changing it and yes, it would require a 2.X release as it changes the API (role names)

**Comment by swapdisk** [comment]
With #40 merged, I think we have addressed all of the concerns. We'll wait for the validated content folks to take a fresh look before closing this.

**Comment by ericzolf** [comment]
> I like the idea of splitting the `lvm_snaphosts` role. Furthermore, I found that it contains the actions `check_for_resize` and `resize` which should be removed. `resize` is not even implemented in this role and they are both actually implemented in the `shrink_lv` role.

We [recommend](https://redhat-cop.github.io/automation-good-practices/#_naming_things) to name roles like `<object>_<action>` because it alphabetically sorts more nicely, hence `snapshot_{create,remove,revert}`, but no big things, it won't keep me from approving (but you are still welcome to make me 100% happy :wink: ).
 
> Item 3 seems required (though not sure why the `ansible-lint` did not err on it).

It's not linted because you can use a simpler/shorter prefix, which becomes difficult to validate automatically.

> Not sure is item 4 is part of the standard and to me looks redundant, but I don't mind complying.

Why it is _not_ redundant is explained [here](https://redhat-cop.github.io/automation-good-practices/#_prefix_task_names_in_sub_tasks_files_of_roles) (tl;dr: it does make logs more readable and useful).
 
> We need to discuss if the collections' name is still correct, though I understand your concern about changing it and yes, it would require a 2.X release as it changes the API (role names)

I haven't seen the discussion, any decision? As the role has disappeared, it's probably fine anyway.

**Comment by swapdisk** [comment]
> We [recommend](https://redhat-cop.github.io/automation-good-practices/#_naming_things) to name roles like `<object>_<action>` because it alphabetically sorts more nicely, hence `snapshot_{create,remove,revert}`, but no big things, it won't keep me from approving (but you are still welcome to make me 100% happy 😉 ).

I knew there was a reason not to push out the 2.0 release yet. I like this suggestion, so no problem renaming the roles to make you 100% happy!

**Comment by swapdisk** [comment]
@ericzolf, the snapshot roles are now renamed like `<object>_<action>` with just merged PR #50.
