### ISSUE TITLE
Failure using bigboot with nvme block devices

### ISSUE THREAD

**Issue by swapdisk** [redhat-cop/infra.lvm_snapshots#48]
Uncovered a couple related issues while testing `bigboot` role on a RHEL7 instance with nvme block devices. The main issue is that the device special file for the boot partition is not being detected correctly. Here's is an example of the script invocation and resulting error output... 

```
switch_root:/# /usr/bin/bigboot.sh -d="/dev/nvme0n1" -s="800M" -b="1" -p="p"
Device (/dev/nvme0n1) not found
...
```

Following this error message, the `bigboot.sh` script also then output a lengthy usage message which leads to the next issue. The output is too much for `/dev/kmsg`, so rather than seeing the error on the console, we observed this... 

```
[    7.740073] dracut-pre-mount[377]: //lib/dracut/hooks/pre-mount/99-increase-boot-partition.sh: line 27: echo: write error: Invalid argument
```

This resulted in some fun head scratching, but we were finally able to figure out the root cause by adding `rd.break=pre-mount` kernel param and then manually running the script at the emergency shell prompt. 

So there are a few things I want to fix here: 

- Figure out why `bigboot.sh` is getting "device not found" error. 
- Don't output the lengthy usage message when there is any error and correct some inaccuracies.
- Maybe find a sysfs way to identify the actual device names rather than messing prefix strings and partition numbers.

**Comment by ygalblum** [comment]
@swapdisk what's the correct device? These parameters are passed to the script by the Ansible role code. Are `-b="1"` and `-p="p"` correct?

**Comment by swapdisk** [comment]
These are the device names from the instance... 
```
# lsblk -p
NAME                                MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
/dev/nvme0n1                        259:0    0   32G  0 disk 
├─/dev/nvme0n1p1                    259:1    0  476M  0 part /boot
└─/dev/nvme0n1p2                    259:2    0 29.5G  0 part 
  ├─/dev/mapper/VolGroup00-rootVol  253:0    0    7G  0 lvm  /
  ├─/dev/mapper/VolGroup00-swapVol  253:1    0    1G  0 lvm  [SWAP]
  ├─/dev/mapper/VolGroup00-homeVol  253:2    0    2G  0 lvm  /home
  ├─/dev/mapper/VolGroup00-varVol   253:3    0    6G  0 lvm  /var
  ├─/dev/mapper/VolGroup00-logVol   253:4    0    2G  0 lvm  /var/log
  ├─/dev/mapper/VolGroup00-auditVol 253:5    0    1G  0 lvm  /var/log/audit
  └─/dev/mapper/VolGroup00-dataVol  253:6    0    1G  0 lvm  /data
```

The parameters we see configured by the role code were `-d="/dev/nvme0n1" -s="800M" -b="1" -p="p"`.
