### ISSUE TITLE
Lint and sanity errors

### ISSUE THREAD

**Issue by swapdisk** [redhat-cop/infra.lvm_snapshots#55]
With the release to Automation Hub, we see a number of (primarily formatting) errors from the ansible-lint test and sanity tests pep8, pylint, and shebang. See import log [here](https://console.redhat.com/ansible/automation-hub/repo/validated/infra/lvm_snapshots/import-log/?version=2.0.1).

Can we fix the offending code and also add these tests to our CI workflows?

**Comment by ygalblum** [comment]
Regarding the `ansible-lint` errors, we do run these checks. But, for some reason it seems that these tests disregard our yamllint configuration of `indent-sequences: false` defined [here](https://github.com/redhat-cop/infra.lvm_snapshots/blob/main/.yamllint#L4). What's strange here is that it does seem to pick the space indent configuration of `2`

**Comment by ygalblum** [comment]
Regarding the shebang issues, please see https://github.com/ansible/ansible/issues/78346

**Comment by ygalblum** [comment]
Regarding pylint, we also run it in our CI. Not sure why their run complains on something our doesn't

**Comment by ygalblum** [comment]
We can add `pep8` test to our CI

**Comment by ygalblum** [comment]
PyCodeStyle (pep8) is added to the CI #56

**Comment by swapdisk** [comment]
I'm calling this resolved.
