### ISSUE TITLE
Bigboot can fail if autoactivation property not set

### ISSUE THREAD

**Issue by swapdisk** [redhat-cop/infra.lvm_snapshots#57]
We observed failed bigboot jobs on hosts where all logical volumes do not have autoactivation property set. When this is the case, the `lsblk` commands in `bigboot.sh` don't detect that the next partition holds an LVM physical volume. That leads to the `pvresize` not being done and then it all goes come-a-gutsa from there! Recommend fixing this by doing `lvm vgchange -ay`  before kicking off the `bigboot.sh` script.

**Comment by swapdisk** [comment]
@jchristianh - I'll leave this to you. Thanks!

**Comment by jchristianh** [comment]
@swapdisk Please review and test the proposed fix. Thanks!
