### ISSUE TITLE
Adding Btrfs support for BigBoot and snapshot management (potentially renaming this repo once both Btrfs and LVM are supported?)

### ISSUE THREAD

**Issue by Conan-Kudo** [redhat-cop/infra.lvm_snapshots#68]
I became aware of BigBoot as part of this project last week at Red Hat Summit, and it looks like it would be very useful for a use-case that I'm trying to deal with: the ever-growing size of firmware included in initramfs (particularly the NVIDIA GSP firmware). One system that I'm dealing with as part of testing stuff, the initramfs images have grown from 30~60MB to ~300MB. This fills up the partition that has the initramfs images (usually `/boot`, which is ext4).

It would be great if we can extend this to support Btrfs and leverage Btrfs' online resize capabilities to shift things around and expand `/boot` as well as the other features of this project as I see a lot of potential in this for Fedora and CentOS Hyperscale users in addition to the RHEL users this is currently targeted at.

cc: @davide125 @michel-slm @dbrandonjohnson

**Comment by swapdisk** [comment]
Hi @Conan-Kudo, thank you for opening the issue. Let me know if you or one of the folks you tagged wants to work up a PR for this? Otherwise, I'll add it to my (long) backlog.

**Comment by swapdisk** [comment]
@Conan-Kudo, I just opened PR #72 that I hope will satisfy your use case. I've tested successfully with Fedora 39 and 40 using Btrfs as well as an older Fedora host that was using LVM. Also verified everything still works the same for RHEL 7-8-9 with LVM. Please let me know if you can test and review?

**Comment by Conan-Kudo** [comment]
For sure I'll look at it!
